css:
    lib:
        - bundles/pimui/lib/bootstrap/css/bootstrap.less
        - bundles/pimui/lib/font-awesome/css/font-awesome.css
        - bundles/pimui/lib/bootstrap-switch/bootstrap.switch.css
        - bundles/pimui/lib/bootstrap-datetimepicker/css/bootstrap-datepicker.css
        - bundles/pimui/lib/select2/select2.css
        - bundles/pimui/lib/jstree/themes/default/style.css
        - bundles/pimui/lib/slimbox2/slimbox2.css
        - bundles/pimui/lib/summernote/summernote.css
    pim_ui:
        - bundles/pimui/css/less/oro.less
        - bundles/pimui/css/all.less
        - bundles/pimui/css/sidebarized.less
        - bundles/pimui/css/jquery-ui.grid.less
        - bundles/pimui/css/icons.less
        - bundles/pimui/css/header.less
        - bundles/pimui/css/pinbar.less
        - bundles/pimui/css/select2.less
        - bundles/pimui/css/form.less
        - bundles/pimui/css/wizard.less
        - bundles/pimui/css/tree.less
        - bundles/pimui/css/dialog.less
        - bundles/pimui/css/modal.less
        - bundles/pimui/css/progress.less
        - bundles/pimui/css/pim.less
        - bundles/pimui/css/signin.less
        - bundles/pimui/css/flags.less
        - bundles/pimui/css/style.less
        - bundles/pimui/css/tabnav.less
        - bundles/pimui/css/buttons.less
        - bundles/pimui/css/accordion.less
        - bundles/pimui/css/filterbox.less
        - bundles/pimui/css/notifications.less
    bem:
#        - bundles/pimui/less/redBorder.less # Please remove this class before merge!
        - bundles/pimui/less/base/general.less
        - bundles/pimui/less/components/actionsPanel.less
        - bundles/pimui/less/components/bell.less
        - bundles/pimui/less/components/breadcrumb.less
        - bundles/pimui/less/components/breadcrumbContainer.less
        - bundles/pimui/less/components/button.less
        - bundles/pimui/less/components/buttonsList.less
        - bundles/pimui/less/components/dropdown.less
        - bundles/pimui/less/components/gridToolbar.less
        - bundles/pimui/less/components/header.less
        - bundles/pimui/less/components/iconButton.less
        - bundles/pimui/less/components/mainMenu.less
        - bundles/pimui/less/components/pagination.less
        - bundles/pimui/less/components/titleContainer.less
        - bundles/pimui/less/components/userMenu.less
